#17 details views
blumilksoftware/meetup pull request #107
Opened 2022-05-08 18:29 UTC by JakubZakowicz

i have created views for meetup, organization, speaker and news details

- meetup details
![screenshot-localhost-2022 05 08-13_37_23](https://user-images.githubusercontent.com/63516552/167310082-a1779d0e-e407-48b1-9586-f77a17e11b21.png)

- organization details
![screenshot-localhost-2022 05 08-13_38_03](https://user-images.githubusercontent.com/63516552/167310110-30bd333b-1e1a-4f66-b75e-26fa879fd160.png)

- speaker details
![screenshot-localhost-2022 05 08-13_38_56](https://user-images.githubusercontent.com/63516552/167310130-027da5f4-9bb6-4a9d-821b-432236394bdc.png)

- news details
![screenshot-localhost-2022 05 08-14_42_29](https://user-images.githubusercontent.com/63516552/167310169-8dea3ea7-7785-4d18-a1c9-21ab7bea3613.png)

Should close #17, #19, #21, #28

2022-05-12 07:19 UTC, krzysztofrewak requested changes

2022-05-12 07:19 UTC, krzysztofrewak commented on src/Http/Routing/WebRouting.php
> +}
```suggestion
}

```

2022-05-13 05:23 UTC, kamilpiech97 requested changes

2022-05-13 05:23 UTC, kamilpiech97 commented on resources/views/organizations/show.blade.php
> +              <a href="#" class="text-sky-700"><i class="fa-brands fa-linkedin fa-xl"></i></a>
What about that links?

2022-05-13 05:23 UTC, kamilpiech97 commented on src/View/Components/backButton.php
> +        public $url,
Typing

2022-05-16 04:16 UTC, kamilpiech97 approved these changes

2022-05-20 04:30 UTC, kamilpiech97 approved these changes

2022-05-31 07:50 UTC, krzysztofrewak approved these changes

2022-05-31 08:00 UTC, merged