#23 - contact page
blumilksoftware/meetup pull request #40
Opened 2022-03-27 19:40 UTC by MichalMyskow

I have created a basic contact page that stores data in a database and sends along with emails.

- model and migration;
- controller and form request;
- observer with notification;
- basic routing;
- basic views;

Should close #23

2022-03-28 04:16 UTC, kamilpiech97 commented on src/Http/Requests/Contact/StoreContactRequest.php
> +            "message" => "required",
If we are  using in `FormRequest` classes array of strings, in that class we should do this also.

2022-03-29 04:12 UTC, kamilpiech97 submitted a review, later dismissed

2022-03-29 06:16 UTC, mtracz requested changes

2022-03-29 06:16 UTC, mtracz commented on src/Models/Contact.php
> +            env("MAIL_FROM_ADDRESS") => env("MAIL_FROM_NAME"),
Don't use `env()`. Use `config()` instead. If you cache config, then `env()` method will return null.
https://laravel.com/docs/9.x/helpers#method-env

2022-03-29 12:59 UTC, mtracz submitted a review, later dismissed

2022-03-30 07:07 UTC, krzysztofrewak submitted a review, later dismissed

2022-03-30 07:45 UTC, kamilpiech97 submitted a review, later dismissed

2022-03-30 07:58 UTC, MrHDOLEK submitted a review, later dismissed

2022-03-30 10:31 UTC, krzysztofrewak approved these changes

2022-03-30 10:35 UTC, kamilpiech97 approved these changes

2022-03-30 10:42 UTC, merged