#18 - add organizations list
blumilksoftware/meetup pull request #66
Opened 2022-04-21 19:32 UTC by JakubZakowicz

I have created simple views for organizations list and forms to create and edit them and to organizations profiles

2022-04-25 11:25 UTC, kamilpiech97 requested changes

2022-04-25 11:25 UTC, kamilpiech97 commented on resources/views/components/form-input.blade.php
> +        {{ $name }}
```suggestion
        {{ $label }}
```

2022-04-25 11:25 UTC, kamilpiech97 commented on resources/views/components/form-input.blade.php
> +            placeholder="{{ $name }}..." value="{{ $value }}"
```suggestion
            placeholder="{{ $placeholder }}" value="{{ $value }}"
```

2022-04-25 11:25 UTC, kamilpiech97 commented on resources/views/components/form-input.blade.php
> +        <input type="{{ $type }}" name="{{ $id }}" id="{{ $id }}"
```suggestion
        <input type="{{ $type }}" name="{{ $field }}" id="{{ $id }}"
```
I would add more readable variable for name attribute.

2022-04-25 11:25 UTC, kamilpiech97 commented on src/Models/Organization.php
> + * @property string $numberOfEmployees
I think `numberOfEmployers` should be an integer.

2022-04-25 11:25 UTC, kamilpiech97 commented on database/migrations/2022_03_09_170615_create_organizations_table.php
> +            $table->string("number_of_employees");
Please create new one migration for incoming changes in `organizations` table.

2022-04-25 11:25 UTC, kamilpiech97 commented on database/migrations/2022_03_09_170615_create_organizations_table.php
> +            $table->string("number_of_employees");
You should not changing existing migrations which were created in another PR.

2022-04-26 04:56 UTC, kamilpiech97 requested changes

2022-04-26 04:56 UTC, kamilpiech97 commented on resources/views/meetups/create.blade.php
> +            <x-form-input id="date" field="date" label="Date" placeholder="Date..." type="datetime-local"
```suggestion
            <x-form-input id="date" field="date" label="Date" placeholder="Date" type="datetime-local"
```
I would prefer delete that `...` in placeholders.

2022-04-27 23:09 UTC, MichalMyskow requested changes

2022-04-27 23:09 UTC, MichalMyskow commented on database/factories/OrganizationFactory.php
> +            "logo_path" => $this->faker->url(),
```suggestion
```
You should delete this line, we are creating `logo_path` with model.

2022-04-27 23:09 UTC, MichalMyskow commented on src/Http/Requests/Organization/StoreOrganizationRequest.php
> +            "logo" => ["required", "image", "max:2048"],
```suggestion
            "logo" => ["image", "max:2048"],
```
Logo is not required when we have default logo system.

2022-04-27 23:13 UTC, MichalMyskow reviewed
`organization_logo.jpeg` file should be removed.

2022-04-29 07:31 UTC, merged