#77 - add contact page
blumilksoftware/meetup pull request #78
Opened 2022-04-25 23:13 UTC by JakubZakowicz

I have created a view for contact page.
![screenshot-localhost-2022 04 26-01_11_09](https://user-images.githubusercontent.com/63516552/165189348-671a0e5d-4832-4641-b4a5-10003187e20a.png)

This should close #77

2022-04-26 04:19 UTC, kamilpiech97 approved these changes

2022-04-26 06:46 UTC, mtracz requested changes

2022-04-26 06:46 UTC, mtracz commented on resources/views/contact.blade.php
> +                  <span class="ml-3">+1 (555) 123-4567</span>
Maybe let's add "callable" phone?
```html
<a href="tel:123-456-7890">123-456-7890</a>
```

2022-04-26 06:46 UTC, mtracz commented on resources/views/contact.blade.php
> +                  <span class="ml-3">support@workcation.com</span>
Maybe let's add "sendable" mail?
```html
<a href= "mailto:abc@example.com">Send Email</a>
```

2022-04-27 06:42 UTC, mtracz approved these changes

2022-04-27 07:26 UTC, MichalMyskow approved these changes

2022-04-27 07:29 UTC, merged