#63 -  add node to docker-compose
blumilksoftware/meetup pull request #95
Opened 2022-05-01 20:46 UTC by MrHDOLEK

Should close https://github.com/blumilksoftware/meetup/issues/63

2022-05-02 13:09 UTC, krzysztofrewak requested changes

2022-05-02 13:09 UTC, krzysztofrewak commented on .env.example
> +NODE_PORT=3000
Please cleanup `.env.example` file. External ports should be in one place.

2022-05-04 04:37 UTC, kamilpiech97 requested changes

2022-05-04 04:37 UTC, kamilpiech97 commented on docker-compose.yml
> +      -  ${NODE_PORT}:3000
Maybe set name node port to `EXTERNAL_NODE_PORT`. Redis need this too.

2022-05-05 06:28 UTC, krzysztofrewak approved these changes

2022-05-05 07:21 UTC, kamilpiech97 approved these changes

2022-05-05 10:20 UTC, merged