#85 -  fix bug for show content a other browsers
blumilksoftware/meetup pull request #97
Opened 2022-05-01 22:31 UTC by MrHDOLEK

Should close https://github.com/blumilksoftware/meetup/issues/85

2022-05-02 10:33 UTC, JakubZakowicz approved these changes

2022-05-02 13:13 UTC, krzysztofrewak requested changes

2022-05-02 13:13 UTC, krzysztofrewak commented on src/Http/Controllers/StaticController.php
> +            "Content-Type" => File::extension($path) === self::FILE_CSS_EXTENSION ? null : File::type($path),
```suggestion
            "Content-Type" => File::extension($path) === static::FILE_CSS_EXTENSION ? null : File::type($path),
```

2022-05-02 13:13 UTC, krzysztofrewak commented on src/Http/Controllers/StaticController.php
> +            "Content-Type" => File::extension($path) === self::FILE_CSS_EXTENSION ? null : File::type($path),
Also: I don't like narrowing to for CSS files only. Maybe renamed const should be an array of strings/types?

2022-05-04 12:55 UTC, krzysztofrewak requested changes

2022-05-04 12:55 UTC, krzysztofrewak commented on src/Http/Controllers/StaticController.php
> +    private const FILE_EXTENSION = [
Oh, come on, this constant name doesn't tell anything about its content. Please make it more verbose.

2022-05-05 06:30 UTC, krzysztofrewak requested changes
IGNORED_FILES would be nice too.

2022-05-05 06:30 UTC, krzysztofrewak commented on src/Http/Controllers/StaticController.php
> +    private const IGNORE_HEADER_FILES_EXTENSION = [
```suggestion
    private const IGNORED_HEADER_FILES_EXTENSIONS = [
```

2022-05-05 17:09 UTC, krzysztofrewak approved these changes

2022-05-05 17:13 UTC, JakubZakowicz approved these changes

2022-05-05 17:14 UTC, merged