#87 - add pagination
blumilksoftware/meetup pull request #99
Opened 2022-05-03 21:11 UTC by MrHDOLEK

2022-05-06 04:40 UTC, kamilpiech97 requested changes

2022-05-06 04:40 UTC, kamilpiech97 commented on resources/views/components/input-limits-pagination.blade.php
> +</div>
```suggestion
</div>

```

2022-05-06 04:40 UTC, kamilpiech97 commented on resources/views/meetups/index.blade.php
>                  @foreach ($meetups as $meetup)
Use `forelse`.
```suggestion
                @forelse ($meetups as $meetup)
```

2022-05-06 04:40 UTC, kamilpiech97 commented on src/Http/Controllers/MeetupController.php
> +        $paginationLimit = $request->input("limit");
What about starting value?

2022-05-06 07:27 UTC, MrHDOLEK commented on src/Http/Controllers/MeetupController.php
> +        $paginationLimit = $request->input("limit");
if limit is empty to pagination is 15

2022-05-09 04:48 UTC, kamilpiech97 approved these changes

2022-05-09 06:35 UTC, krzysztofrewak requested changes

2022-05-09 06:35 UTC, krzysztofrewak commented on resources/views/components/input-limits-pagination.blade.php
> +        <option value="{{ route((string)request()->route()->getName(),['limit'=> 100 ]) }}">Limit: 100</option>
```suggestion
        <option value="{{ route((string)request()->route()->getName(), ['limit'=> 10 ]) }}">Limit: 10</option>
        <option value="{{ route((string)request()->route()->getName(), ['limit'=> 30 ]) }}">Limit: 30</option>
        <option value="{{ route((string)request()->route()->getName(), ['limit'=> 50 ]) }}">Limit: 50</option>
        <option value="{{ route((string)request()->route()->getName(), ['limit'=> 100 ]) }}">Limit: 100</option>
```

2022-05-09 06:35 UTC, krzysztofrewak commented on resources/views/components/input-limits-pagination.blade.php
> +        <option value="{{ route((string)request()->route()->getName(),['limit'=> 100 ]) }}">Limit: 100</option>
And do you really need to call router four times? Maybe you could move this value to controller or view composer? Or maybe `#` would be enough?

2022-05-09 06:35 UTC, krzysztofrewak commented on src/Http/Requests/PaginationRequest.php
> +class PaginationRequest extends FormRequest
Are you sure that's a good idea? What if you would like to add pagination to some controller's method what would require other form request? And do you really think that invalid pagination limit should crash application?

2022-05-11 21:42 UTC, Majkulnn commented on database/seeders/DummyDataSeeder.php
> +            "password" => "password",
write back Hash:make here

2022-05-20 04:32 UTC, kamilpiech97 submitted a review, later dismissed

2022-10-24 07:43 UTC, Majkulnn approved these changes

2022-10-24 07:54 UTC, krzysztofrewak approved these changes

2022-10-24 09:17 UTC, merged